# Generated by Django 3.2.9 on 2022-05-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("uf", models.CharField(max_length=2)),
                ("uf_code", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("ibge_code", models.CharField(max_length=255)),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.state")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("zip_code", models.CharField(max_length=12)),
                ("street", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.city")),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
