# Generated by Django 3.2.9 on 2022-05-04 13:28

import json
import os

from django.db import migrations


def loadStates(apps, schema_editor):
    State = apps.get_model("common", "State")
    states_file_path = os.path.join(os.path.dirname(__file__), "estados.json")
    with open(states_file_path, encoding="utf-8-sig") as states_file:
        states = json.load(states_file)
        for state in states:
            State.objects.create(name=state["nome"], uf=state["uf"], uf_code=state["codigo_uf"])


def loadCities(apps, schema_editor):
    City = apps.get_model("common", "City")
    State = apps.get_model("common", "State")
    cities_file_path = os.path.join(os.path.dirname(__file__), "municipios.json")
    with open(cities_file_path, encoding="utf-8-sig") as cities_file:
        cities = json.load(cities_file)
        for city in cities:
            state = State.objects.get(uf_code=city["codigo_uf"])
            City.objects.create(name=city["nome"], state=state, ibge_code=city["codigo_ibge"])


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(loadStates, loadStates),
        migrations.RunPython(loadCities, loadCities),
    ]
