# Generated by Django 3.2.9 on 2022-05-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20220504_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=255, verbose_name="District"),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(max_length=255, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=12, verbose_name="Zip code"),
        ),
        migrations.AlterField(
            model_name="city",
            name="ibge_code",
            field=models.CharField(max_length=255, verbose_name="IBGE code"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.state", verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="state",
            name="uf",
            field=models.CharField(max_length=2, verbose_name="UF"),
        ),
        migrations.AlterField(
            model_name="state",
            name="uf_code",
            field=models.CharField(max_length=255, verbose_name="UF Code"),
        ),
    ]
