# Generated by Django 3.2.9 on 2022-05-05 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Hidden"), (1, "Available"), (2, "Selled")], max_length=50, verbose_name="Status"
            ),
        ),
    ]
