# Generated by Django 3.2.9 on 2022-05-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20220505_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(choices=[(0, "Hidden"), (1, "Available"), (2, "Selled")], verbose_name="Status"),
        ),
    ]
