# Generated by Django 3.2.9 on 2022-06-14 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_auto_20220506_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Favorite'),
        ),
    ]
