# Generated by Django 4.0.6 on 2022-07-09 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_product_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Favorite'),
        ),
    ]
